steps:
# Step 1: Install dependencies and run the stats script
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']

- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'fetch-stats']

# Step 2: Deploy the static files
- name: 'gcr.io/cloud-builders/gsutil'
  args: [
    '-m',
    'rsync',
    '-r',
    '-c',
    '-d',
    '.', # Assuming the files to sync are in the root
    'gs://wedding-snipe-countdown-site'
  ]
options:
  logging: CLOUD_LOGGING_ONLY